services:
  sim1:
    build:
      context: ./smart-meter-simulator
      dockerfile: ./Dockerfile
    environment:
      - SN=HG6789DS
      - CONSUMER=Consumer1
      - SMART_COLLECTOR_BACKEND_URL=localhost:5000
      - DATA_DIR=./data
      - DATA_FILE=Dataset.xlsx
      - DATA_KEYS=Total Production,Total Consumption,AC,Dish washer,Washing Machine,Dryer,Water heater,TV,Microwave,Kettle,Lighting,Refrigerator
    volumes:
      - ./smart-meter-simulator:/root
    entrypoint: ["python", "./src/send.py"]
    tty: true
    user: root
    network_mode: host
  
  sim2:
    build:
      context: ./smart-meter-simulator
      dockerfile: ./Dockerfile
    volumes:
      - ./smart-meter-simulator:/root
    environment:
      - SN=HG678K5F
      - CONSUMER=Consumer2
      - SMART_COLLECTOR_BACKEND_URL=localhost:5000
      - DATA_DIR=./data
      - DATA_FILE=Dataset.xlsx
      - DATA_KEYS=Total Production,Total Consumption,AC,Dish washer,Washing Machine,Dryer,Water heater,TV,Microwave,Kettle,Lighting,Refrigerator
    entrypoint: ["python", "./src/send.py"]
    tty: true
    user: root
    network_mode: host
  
  smart-data-collector:
    build:
      context: ./smart-meter-collector
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    entrypoint: /bin/bash
    tty: true
    user: root
    network_mode: host

  db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      ports:
        - 5432:5432
      network_mode: host
      environment:
        - POSTGRES_PASSWORD=bc4grid

volumes:
  postgres_data: