POST http://localhost:5000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "code": "Consumer1",
    "firstname": "John",
    "lastname": "Williams",
    "email": "somebody@gmail.com",
    "password": "password",
    "smartmeter": {
        "sn": "HG6789DS"
    }
}

POST http://localhost:5000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "code": "Consumer2",
    "firstname": "Henry",
    "lastname": "Hampton",
    "email": "somebody2@gmail.com",
    "password": "password",
    "smartmeter": {
        "sn": "HG678K5F"
    }
}


POST http://localhost:5000/api/v1/smartmeter/54FGX67K/data HTTP/1.1
Content-Type: application/json

{
    "dish_washer": 0.0
}

GET http://localhost:5000/api/v1/smartmeter/1/balance?from=2024-01-04 08:45:00&to=2024-01-04 09:00:00 HTTP/1.1
Content-Type: application/json
